@echo off
chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion
title MENU CONG CU HE THONG
mode con: cols=92 lines=45

:MENU
cls
echo.
echo  ============================================================
echo           MENU CONG CU HE THONG  -  SYSTEM TOOLS
echo  ============================================================
echo.
echo   [1]  Thong tin may tinh
echo   [2]  Backup / Restore Driver
echo   [3]  Sao luu ban quyen Key (Windows / Office)
echo   [4]  Kich hoat Windows / Office (MAS)
echo   [5]  Sao luu du lieu Zalo
echo   [6]  Tat BitLocker
echo   [7]  Don dep tep tin rac
echo   [8]  Tat Windows Update
echo   [9]  Tat Windows Defender
echo.
echo   [0]  THOAT
echo.
echo  ============================================================
echo.
set "choice="
set /p choice="  Chon chuc nang (0-9): "

if "%choice%"=="1" goto INFO
if "%choice%"=="2" goto BACKUP_DRIVER
if "%choice%"=="3" goto SAVE_KEY
if "%choice%"=="4" goto ACTIVATE
if "%choice%"=="5" goto ZALO
if "%choice%"=="6" goto BITLOCKER
if "%choice%"=="7" goto CLEANUP
if "%choice%"=="8" goto DISABLE_UPDATE
if "%choice%"=="9" goto DISABLE_DEFENDER
if "%choice%"=="0" goto EXIT
echo.
echo  [!] Lua chon khong hop le.
timeout /t 2 >nul
goto MENU

:: ============================================================
:INFO
mode con: cols=92 lines=70
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAWwBDAG8AbgBzAG8AbABlAF0AOgA6AE8AdQB0AHAAdQB0AEUAbgBjAG8AZABpAG4AZwA9AFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgACgAkAGgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBCAGEAYwBrAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgA9ACcAQgBsAGEAYwBrACcACgAkAGgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgA9ACcAVwBoAGkAdABlACcACgBDAGwAZQBhAHIALQBIAG8AcwB0AAoACgAkAFcAIAA9ACAAOAAyAAoACgBmAHUAbgBjAHQAaQBvAG4AIABMAG4AIAB7ACAAVwByAGkAdABlAC0ASABvAHMAdAAgACgAJwAgACAAJwAgACsAIAAoAFsAYwBoAGEAcgBdADAAeAAyADUANQAwACkALgBUAG8AUwB0AHIAaQBuAGcAKAApACoAKAAkAFcALQAyACkAKQAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABEAGEAcgBrAEMAeQBhAG4AIAB9AAoAZgB1AG4AYwB0AGkAbwBuACAATABuAFQAaABpAG4AIAB7ACAAVwByAGkAdABlAC0ASABvAHMAdAAgACgAJwAgACAAJwAgACsAIAAoAFsAYwBoAGEAcgBdADAAeAAyADUAMAAwACkALgBUAG8AUwB0AHIAaQBuAGcAKAApACoAKAAkAFcALQAyACkAKQAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABEAGEAcgBrAEcAcgBhAHkAIAB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABUAGkAdABsAGUAKAAkAHQAKQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgAgACAAIAAgAEwAbgAKACAAIAAgACAAJABwAGEAZAAgAD0AIAAnACAAJwAgACoAIABbAE0AYQB0AGgAXQA6ADoATQBhAHgAKAAwACwAWwBNAGEAdABoAF0AOgA6AEYAbABvAG8AcgAoACgAJABXACAALQAgACQAdAAuAEwAZQBuAGcAdABoACAALQAgADIAKQAvADIAKQApAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAiACAAIAAiACAAKwAgACQAcABhAGQAIAArACAAJAB0ACkAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAQwB5AGEAbgAKACAAIAAgACAATABuAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAnAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAUwBlAGMAKAAkAHQAKQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAIAAgAFsAIAAiACAAKwAgACQAdAAgACsAIAAiACAAXQAiACkAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAWQBlAGwAbABvAHcACgAgACAAIAAgAEwAbgBUAGgAaQBuAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAUgBvAHcAKAAkAGwAYQBiAGUAbAAsACAAJAB2AGEAbAB1AGUALAAgACQAdgBjACkAIAB7AAoAIAAgACAAIABpAGYAIAAoAC0AbgBvAHQAIAAkAHYAYwApACAAewAgACQAdgBjACAAPQAgACcAVwBoAGkAdABlACcAIAB9AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAnACAAIAAgACAAewAwACwALQAyADgAfQAnACAALQBmACAAJABsAGEAYgBlAGwAKQAgAC0ATgBvAE4AZQB3AGwAaQBuAGUAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARABhAHIAawBHAHIAYQB5AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJAB2AGEAbAB1AGUAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAJAB2AGMACgB9AAoACgAjACAAUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlIABIAEUAQQBEAEUAUgAgAFAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlUCVQJVAlCgBUAGkAdABsAGUAIAAnAFQASABPAE4ARwAgAFQASQBOACAASABFACAAVABIAE8ATgBHACAAIAB8ACAAIABTAFkAUwBUAEUATQAgAEkATgBGAE8AJwAKAAoAIwAgAAAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUgAEMAUABVACAAACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQoAUwBlAGMAIAAnAEMAUABVACcACgBHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAFcAaQBuADMAMgBfAFAAcgBvAGMAZQBzAHMAbwByACAAfAAgAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsACgAgACAAIAAgAFIAbwB3ACAAJwBUAGUAbgAgAEMAUABVACcAIAAgACAAIAAgACAAIAAgACQAXwAuAE4AYQBtAGUAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJwBXAGgAaQB0AGUAJwAKACAAIAAgACAAUgBvAHcAIAAnAE4AaABhAG4AIAAvACAATAB1AG8AbgBnACcAIAAgACAAIgAkACgAJABfAC4ATgB1AG0AYgBlAHIATwBmAEMAbwByAGUAcwApACAAbgBoAGEAbgAgACAALwAgACAAJAAoACQAXwAuAE4AdQBtAGIAZQByAE8AZgBMAG8AZwBpAGMAYQBsAFAAcgBvAGMAZQBzAHMAbwByAHMAKQAgAGwAdQBvAG4AZwAiACAAIAAnAEcAcgBlAGUAbgAnAAoAIAAgACAAIABSAG8AdwAgACcAWAB1AG4AZwAgAG4AaABpAHAAIABNAGEAeAAnACAAIAAiACQAKAAkAF8ALgBNAGEAeABDAGwAbwBjAGsAUwBwAGUAZQBkACkAIABNAEgAegAiACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAEcAcgBlAGUAbgAnAAoAIAAgACAAIABSAG8AdwAgACcAQQByAGMAaABpAHQAZQBjAHQAdQByAGUAJwAgACAAIAAiACQAKAAkAF8ALgBBAGQAZAByAGUAcwBzAFcAaQBkAHQAaAApAC0AYgBpAHQAIgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAEQAYQByAGsARwByAGEAeQAnAAoAfQAKAAoAIwAgAAAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUgAFIAQQBNACAAACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQoAUwBlAGMAIAAnAFIAQQBNACcACgAkAHMAbABvAHQAcwAgAD0AIAAwAAoARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBQAGgAeQBzAGkAYwBhAGwATQBlAG0AbwByAHkAIAB8ACAARgBvAHIARQBhAGMAaAAtAE8AYgBqAGUAYwB0ACAAewAKACAAIAAgACAAJABzAGwAbwB0AHMAKwArAAoAIAAgACAAIAAkAGcAYgAgACAAIAA9ACAAWwBNAGEAdABoAF0AOgA6AFIAbwB1AG4AZAAoACQAXwAuAEMAYQBwAGEAYwBpAHQAeQAvADEARwBCACwAIAAwACkACgAgACAAIAAgACQAdAB5AHAAZQAgAD0AIABzAHcAaQB0AGMAaAAgACgAJABfAC4ATQBlAG0AbwByAHkAVAB5AHAAZQApACAAewAgADIAMAB7ACcARABEAFIAJwB9ACAAMgAxAHsAJwBEAEQAUgAyACcAfQAgADIANAB7ACcARABEAFIAMwAnAH0AIAAyADYAewAnAEQARABSADQAJwB9ACAAMwA0AHsAJwBEAEQAUgA1ACcAfQAgAGQAZQBmAGEAdQBsAHQAewAnAFIAQQBNACcAfQAgAH0ACgAgACAAIAAgAFIAbwB3ACAAIgAkACgAJABfAC4AQgBhAG4AawBMAGEAYgBlAGwAKQAgAC8AIABTAGwAbwB0ACAAJABzAGwAbwB0AHMAIgAgACAAIgAkAGcAYgAgAEcAQgAgACAAIAAkAHsAdAB5AHAAZQB9ACAAIAAgACQAKAAkAF8ALgBTAHAAZQBlAGQAKQAgAE0ASAB6ACAAIAAgACQAKAAkAF8ALgBNAGEAbgB1AGYAYQBjAHQAdQByAGUAcgApACIAIAAgACcAQwB5AGEAbgAnAAoAfQAKACQAdABvAHQAYQBsACAAPQAgAFsATQBhAHQAaABdADoAOgBSAG8AdQBuAGQAKAAoAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8AQwBvAG0AcAB1AHQAZQByAFMAeQBzAHQAZQBtACkALgBUAG8AdABhAGwAUABoAHkAcwBpAGMAYQBsAE0AZQBtAG8AcgB5AC8AMQBHAEIALAAgADIAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBSAG8AdwAgACcAVABvAG4AZwAgAGMAbwBuAGcAIABSAEEATQAnACAAIAAiACQAdABvAHQAYQBsACAARwBCACIAIAAgACcAQwB5AGEAbgAnAAoAJABtAGUAbQBBAHIAcgBhAHkAIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBQAGgAeQBzAGkAYwBhAGwATQBlAG0AbwByAHkAQQByAHIAYQB5ACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADEACgBpAGYAIAAoACQAbQBlAG0AQQByAHIAYQB5ACkAIAB7AAoAIAAgACAAIAAkAG0AYQB4AEcAQgAgACAAIAAgAD0AIABbAE0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJABtAGUAbQBBAHIAcgBhAHkALgBNAGEAeABDAGEAcABhAGMAaQB0AHkAIAAvACAAKAAxADAAMgA0ACoAMQAwADIANAApACwAIAAwACkACgAgACAAIAAgACQAbgB1AG0AUwBsAG8AdABzACAAPQAgACQAbQBlAG0AQQByAHIAYQB5AC4ATQBlAG0AbwByAHkARABlAHYAaQBjAGUAcwAKACAAIAAgACAAUgBvAHcAIAAnAFIAQQBNACAAdABvAGkAIABkAGEAIABoAG8AIAB0AHIAbwAnACAAIAAgACIAJABtAGEAeABHAEIAIABHAEIAIAAgACgAJABuAHUAbQBTAGwAbwB0AHMAIABzAGwAbwB0AHMAKQAiACAAIAAnAE0AYQBnAGUAbgB0AGEAJwAKACAAIAAgACAAJABmAHIAZQBlAFMAbABvAHQAcwAgAD0AIAAkAG4AdQBtAFMAbABvAHQAcwAgAC0AIAAkAHMAbABvAHQAcwAKACAAIAAgACAAaQBmACAAKAAkAGYAcgBlAGUAUwBsAG8AdABzACAALQBnAHQAIAAwACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAFIAbwB3ACAAJwBTAGwAbwB0ACAAYwBvAG4AIAB0AHIAbwBuAGcAJwAgACAAIgAkAGYAcgBlAGUAUwBsAG8AdABzACAAcwBsAG8AdAAoAHMAKQAiACAAIAAnAFkAZQBsAGwAbwB3ACcACgAgACAAIAAgAH0AIABlAGwAcwBlACAAewAKACAAIAAgACAAIAAgACAAIABSAG8AdwAgACcAUwBsAG8AdAAgAGMAbwBuACAAdAByAG8AbgBnACcAIAAgACcARABhAHkAIAAoADAAIABzAGwAbwB0ACkAJwAgACAAJwBEAGEAcgBrAEcAcgBhAHkAJwAKACAAIAAgACAAfQAKAH0ACgAKACMAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlIABWAEcAQQAgAAAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUKAFMAZQBjACAAJwBDAEEAUgBEACAARABPACAASABPAEEAJwAKAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8AVgBpAGQAZQBvAEMAbwBuAHQAcgBvAGwAbABlAHIAIAB8ACAARgBvAHIARQBhAGMAaAAtAE8AYgBqAGUAYwB0ACAAewAKACAAIAAgACAAJAB2AHIAYQBtAEcAQgAgAD0AIABpAGYAIAAoACQAXwAuAEEAZABhAHAAdABlAHIAUgBBAE0AIAAtAGcAdAAgADAAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIgAkACgAWwBNAGEAdABoAF0AOgA6AFIAbwB1AG4AZAAoACQAXwAuAEEAZABhAHAAdABlAHIAUgBBAE0ALwAxAEcAQgAsACAAMgApACkAIABHAEIAIgAKACAAIAAgACAAfQAgAGUAbABzAGUAIAB7ACAAIgBOAC8AQQAiACAAfQAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIAAgACAAIAAkACgAJABfAC4ATgBhAG0AZQApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAVwBoAGkAdABlAAoAIAAgACAAIABSAG8AdwAgACcAIAAgAFYAUgBBAE0AJwAgACAAIAAgACQAdgByAGEAbQBHAEIAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAEcAcgBlAGUAbgAnAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAnAAoAfQAKAAoAIwAgAAAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJSAATwAgAEMAVQBOAEcAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQoAUwBlAGMAIAAnAE8AIABDAFUATgBHACcACgAKACMAIABMAGEAeQAgAHQAbwBhAG4AIABiAG8AIABTAE0AQQBSAFQAIABpAG4AcwB0AGEAbgBjAGUAcwAgAHQAcgB1AG8AYwAKACQAYQBsAGwAUwBtAGEAcgB0AEQAYQB0AGEAIAAgACAAPQAgAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAALQBOAGEAbQBlAHMAcABhAGMAZQAgAHIAbwBvAHQAXAB3AG0AaQAgAC0AQwBsAGEAcwBzAE4AYQBtAGUAIABNAFMAUwB0AG8AcgBhAGcAZQBEAHIAaQB2AGUAcgBfAEYAYQBpAGwAdQByAGUAUAByAGUAZABpAGMAdABEAGEAdABhACAAIAAgADIAPgAkAG4AdQBsAGwACgAkAGEAbABsAFMAbQBhAHIAdABUAGgAcgBlAHMAaAAgAD0AIABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAC0ATgBhAG0AZQBzAHAAYQBjAGUAIAByAG8AbwB0AFwAdwBtAGkAIAAtAEMAbABhAHMAcwBOAGEAbQBlACAATQBTAFMAdABvAHIAYQBnAGUARAByAGkAdgBlAHIAXwBGAGEAaQBsAHUAcgBlAFAAcgBlAGQAaQBjAHQAVABoAHIAZQBzAGgAbwBsAGQAcwAgADIAPgAkAG4AdQBsAGwACgAKACMAIAAlACAAcwB1ACAAZAB1AG4AZwAgAHQAaQBuAGgAIABjAGgAdQBuAGcAIAAxACAAbABhAG4ACgAkAGYAcgBlAGUAVABvAHQAYQBsACAAPQAgADAAOwAgACQAcwBpAHoAZQBUAG8AdABhAGwAIAA9ACAAMAAKAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8ATABvAGcAaQBjAGEAbABEAGkAcwBrACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEQAcgBpAHYAZQBUAHkAcABlACAALQBlAHEAIAAzACAAfQAgAHwAIABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7AAoAIAAgACAAIAAkAHMAaQB6AGUAVABvAHQAYQBsACAAKwA9ACAAJABfAC4AUwBpAHoAZQA7ACAAJABmAHIAZQBlAFQAbwB0AGEAbAAgACsAPQAgACQAXwAuAEYAcgBlAGUAUwBwAGEAYwBlAAoAfQAKAAoARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBEAGkAcwBrAEQAcgBpAHYAZQAgAHwAIABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7AAoAIAAgACAAIAAkAGQAaQBzAGsAIAAgACAAPQAgACQAXwAKACAAIAAgACAAJAByAGEAdwBHAEIAIAAgAD0AIABbAE0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJABkAGkAcwBrAC4AUwBpAHoAZQAgAC8AIAAxADAAMAAwADAAMAAwADAAMAAwACwAIAAwACkACgAgACAAIAAgACQAcgBlAGEAbABHAEIAIAA9ACAAWwBNAGEAdABoAF0AOgA6AFIAbwB1AG4AZAAoACQAZABpAHMAawAuAFMAaQB6AGUAIAAvACAAMQAwADcAMwA3ADQAMQA4ADIANAAsACAAMQApAAoAIAAgACAAIAAkAG0AbwBkAGUAbAAgACAAPQAgACQAZABpAHMAawAuAE0AbwBkAGUAbAAKACAAIAAgACAAJABpAGQAeAAgACAAIAAgAD0AIAAkAGQAaQBzAGsALgBJAG4AZABlAHgACgAKACAAIAAgACAAIwAgAEIAdQBzACAAdAB5AHAAZQAKACAAIAAgACAAJABtAGUAZABpAGEAVAB5AHAAZQAgAD0AIAAkAGQAaQBzAGsALgBNAGUAZABpAGEAVAB5AHAAZQA7ACAAJABiAHUAcwBUAHkAcABlACAAPQAgACcAVQBuAGsAbgBvAHcAbgAnAAoAIAAgACAAIAB0AHIAeQAgAHsACgAgACAAIAAgACAAIAAgACAAJABtAGQAIAA9ACAARwBlAHQALQBQAGgAeQBzAGkAYwBhAGwARABpAHMAawAgAHwAIABXAGgAZQByAGUALQBPAGIAagBlAGMAdAAgAHsAIAAkAF8ALgBEAGUAdgBpAGMAZQBJAGQAIAAtAGUAcQAgACQAaQBkAHgAIAB9ACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADEACgAgACAAIAAgACAAIAAgACAAaQBmACAAKAAtAG4AbwB0ACAAJABtAGQAKQAgAHsAIAAkAG0AZAAgAD0AIABHAGUAdAAtAFAAaAB5AHMAaQBjAGEAbABEAGkAcwBrACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEYAcgBpAGUAbgBkAGwAeQBOAGEAbQBlACAALQBsAGkAawBlACAAIgAqACQAKAAkAG0AbwBkAGUAbAAuAFMAdQBiAHMAdAByAGkAbgBnACgAMAAsAFsATQBhAHQAaABdADoAOgBNAGkAbgAoADEAMgAsACQAbQBvAGQAZQBsAC4ATABlAG4AZwB0AGgAKQApACkAKgAiACAAfQAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBGAGkAcgBzAHQAIAAxACAAfQAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAbQBkACkAIAB7ACAAJABiAHUAcwBUAHkAcABlACAAPQAgACQAbQBkAC4AQgB1AHMAVAB5AHAAZQA7ACAAJABtAGUAZABpAGEAVAB5AHAAZQAgAD0AIAAkAG0AZAAuAE0AZQBkAGkAYQBUAHkAcABlACAAfQAKACAAIAAgACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKACAAIAAgACAAaQBmACAAKAAkAGIAdQBzAFQAeQBwAGUAIAAtAGUAcQAgACcAVQBuAGsAbgBvAHcAbgAnACAALQBvAHIAIAAkAGIAdQBzAFQAeQBwAGUAIAAtAGUAcQAgACcAJwApACAAewAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAbQBvAGQAZQBsACAALQBtAGEAdABjAGgAIAAnAE4AVgBNAGUAfABOAFYATQBFAHwAUABDAEkAZQB8AFAAQwBJAEUAJwApACAAewAgACQAYgB1AHMAVAB5AHAAZQAgAD0AIAAnAE4AVgBNAGUAJwAgAH0ACgAgACAAIAAgACAAIAAgACAAZQBsAHMAZQBpAGYAIAAoACQAZABpAHMAawAuAEkAbgB0AGUAcgBmAGEAYwBlAFQAeQBwAGUAIAAtAG0AYQB0AGMAaAAgACcAUwBDAFMASQB8AEkARABFACcAKQAgAHsAIAAkAGIAdQBzAFQAeQBwAGUAIAA9ACAAJABkAGkAcwBrAC4ASQBuAHQAZQByAGYAYQBjAGUAVAB5AHAAZQAgAH0ACgAgACAAIAAgACAAIAAgACAAZQBsAHMAZQAgAHsAIAAkAGIAdQBzAFQAeQBwAGUAIAA9ACAAJABkAGkAcwBrAC4ASQBuAHQAZQByAGYAYQBjAGUAVAB5AHAAZQAgAH0ACgAgACAAIAAgAH0ACgAgACAAIAAgACQAZAByAGkAdgBlAFQAeQBwAGUAIAAgAD0AIABpAGYAIAAoACQAYgB1AHMAVAB5AHAAZQAgAC0AZQBxACAAJwBOAFYATQBlACcAIAAtAG8AcgAgACQAbQBvAGQAZQBsACAALQBtAGEAdABjAGgAIAAnAE4AVgBNAGUAfABOAFYATQBFAHwAUABDAEkAZQAnACkAIAB7ACAAJwBOAFYATQBlACAAKABQAEMASQBlACAATQAuADIAKQAnACAAfQAgAGUAbABzAGUAaQBmACAAKAAkAGIAdQBzAFQAeQBwAGUAIAAtAGUAcQAgACcAUwBBAFQAQQAnACkAIAB7ACAAJwBTAEEAVABBACcAIAB9ACAAZQBsAHMAZQBpAGYAIAAoACQAYgB1AHMAVAB5AHAAZQAgAC0AZQBxACAAJwBVAFMAQgAnACkAIAB7ACAAJwBVAFMAQgAnACAAfQAgAGUAbABzAGUAIAB7ACAAJABiAHUAcwBUAHkAcABlACAAfQAKACAAIAAgACAAJABtAGUAZABpAGEATABhAGIAZQBsACAAPQAgAGkAZgAgACgAJABtAGUAZABpAGEAVAB5AHAAZQAgAC0AbQBhAHQAYwBoACAAJwBTAFMARAB8AFMAbwBsAGkAZAB8AFUAbgBzAHAAZQBjAGkAZgBpAGUAZAAnACkAIAB7ACAAJwBTAFMARAAnACAAfQAgAGUAbABzAGUAaQBmACAAKAAkAG0AZQBkAGkAYQBUAHkAcABlACAALQBtAGEAdABjAGgAIAAnAEgARABEAHwARgBpAHgAZQBkAHwARQB4AHQAZQByAG4AYQBsACcAKQAgAHsAIAAnAEgARABEACcAIAB9ACAAZQBsAHMAZQAgAHsAIAAnAFMAUwBEAC8ASABEAEQAJwAgAH0ACgAKACAAIAAgACAAIwAgAFMATQBBAFIAVAAgAC0AIABtAGEAdABjAGgAIAB0AGgAZQBvACAASQBuAHMAdABhAG4AYwBlAE4AYQBtAGUAIABjAGgAdQBhACAAcwBvACAAaABpAGUAdQAgAGQAaQBzAGsAIAAoAGQAaQBzAGsALgBiAGkAbgAsACAARABpAHMAawAgACMATgAsACAAXwBOAF8AKQAKACAAIAAgACAAJABzAG0AYQByAHQASQBuAHMAdAAgACAAPQAgACQAYQBsAGwAUwBtAGEAcgB0AEQAYQB0AGEAIAAgACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEkAbgBzAHQAYQBuAGMAZQBOAGEAbQBlACAALQBtAGEAdABjAGgAIAAiAGQAaQBzAGsAXAAuAGIAaQBuAF8AJABpAGQAeABcAGIAfABEAGkAcwBrACAAIwAkAGkAZAB4AFwAYgB8AF8AJAB7AGkAZAB4AH0AXwAwAFwAYgB8AGQAaQBzAGsAJAB7AGkAZAB4AH0AIgAgAH0AIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQAKACAAIAAgACAAJAB0AGgAcgBlAHMAaABJAG4AcwB0ACAAPQAgACQAYQBsAGwAUwBtAGEAcgB0AFQAaAByAGUAcwBoACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEkAbgBzAHQAYQBuAGMAZQBOAGEAbQBlACAALQBtAGEAdABjAGgAIAAiAGQAaQBzAGsAXAAuAGIAaQBuAF8AJABpAGQAeABcAGIAfABEAGkAcwBrACAAIwAkAGkAZAB4AFwAYgB8AF8AJAB7AGkAZAB4AH0AXwAwAFwAYgB8AGQAaQBzAGsAJAB7AGkAZAB4AH0AIgAgAH0AIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQAKAAoAIAAgACAAIAAjACAATgBlAHUAIABrAGgAbwBuAGcAIABtAGEAdABjAGgAIAB0AGgAZQBvACAAaQBuAGQAZQB4ACwAIAB0AGgAdQAgAG0AYQB0AGMAaAAgAHQAaABlAG8AIAB2AGkAIAB0AHIAaQAgAHQAcgBvAG4AZwAgAG0AYQBuAGcAIAAoAGQAaQBzAGsAIAB0AGgAdQAgAE4AKQAKACAAIAAgACAAaQBmACAAKAAtAG4AbwB0ACAAJABzAG0AYQByAHQASQBuAHMAdAAgAC0AYQBuAGQAIAAkAGEAbABsAFMAbQBhAHIAdABEAGEAdABhACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACQAcwBtAGEAcgB0AEkAbgBzAHQAIAAgAD0AIABAACgAJABhAGwAbABTAG0AYQByAHQARABhAHQAYQApAFsAJABpAGQAeABdAAoAIAAgACAAIAAgACAAIAAgACQAdABoAHIAZQBzAGgASQBuAHMAdAAgAD0AIABAACgAJABhAGwAbABTAG0AYQByAHQAVABoAHIAZQBzAGgAKQBbACQAaQBkAHgAXQAKACAAIAAgACAAfQAKAAoAIAAgACAAIAAkAHAAbwB3AGUAcgBPAG4ASABvAHUAcgBzACAAPQAgACcATgAvAEEAJwA7ACAAJABoAGUAYQBsAHQAaABTAHQAcgAgAD0AIAAnAE4ALwBBACcAOwAgACQAaABlAGEAbAB0AGgAQwBvAGwAbwByACAAPQAgACcARABhAHIAawBHAHIAYQB5ACcACgAKACAAIAAgACAAaQBmACAAKAAkAHMAbQBhAHIAdABJAG4AcwB0ACAALQBhAG4AZAAgACQAcwBtAGEAcgB0AEkAbgBzAHQALgBWAGUAbgBkAG8AcgBTAHAAZQBjAGkAZgBpAGMAIAAtAGEAbgBkACAAJABzAG0AYQByAHQASQBuAHMAdAAuAFYAZQBuAGQAbwByAFMAcABlAGMAaQBmAGkAYwAuAEMAbwB1AG4AdAAgAC0AZwB0ACAAMQAyACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACQAdgBzACAAPQAgACQAcwBtAGEAcgB0AEkAbgBzAHQALgBWAGUAbgBkAG8AcgBTAHAAZQBjAGkAZgBpAGMACgAgACAAIAAgACAAIAAgACAAJAB0AHYAIAA9ACAAaQBmACAAKAAkAHQAaAByAGUAcwBoAEkAbgBzAHQAKQAgAHsAIAAkAHQAaAByAGUAcwBoAEkAbgBzAHQALgBWAGUAbgBkAG8AcgBTAHAAZQBjAGkAZgBpAGMAIAB9ACAAZQBsAHMAZQAgAHsAIAAkAG4AdQBsAGwAIAB9AAoAIAAgACAAIAAgACAAIAAgACQAYQB0AHQAcgBzACAAPQAgAEAAewB9AAoAIAAgACAAIAAgACAAIAAgAGYAbwByACAAKAAkAGkAIAA9ACAAMgA7ACAAJABpACAALQBsAGUAIAAoACQAdgBzAC4AQwBvAHUAbgB0ACAALQAgADEAMgApADsAIAAkAGkAIAArAD0AIAAxADIAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAZAAgAD0AIAAkAHYAcwBbACQAaQBdADsAIABpAGYAIAAoACQAaQBkACAALQBlAHEAIAAwACkAIAB7ACAAYwBvAG4AdABpAG4AdQBlACAAfQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAcgBhAHcAIAA9ACAAWwBsAG8AbgBnAF0AJAB2AHMAWwAkAGkAKwA1AF0AIAArACAAKABbAGwAbwBuAGcAXQAkAHYAcwBbACQAaQArADYAXQAgAC0AcwBoAGwAIAA4ACkAIAArACAAKABbAGwAbwBuAGcAXQAkAHYAcwBbACQAaQArADcAXQAgAC0AcwBoAGwAIAAxADYAKQAgACsAIAAoAFsAbABvAG4AZwBdACQAdgBzAFsAJABpACsAOABdACAALQBzAGgAbAAgADIANAApAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABjAHUAcgAgAD0AIABbAGkAbgB0AF0AJAB2AHMAWwAkAGkAKwAzAF0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGEAdAB0AHIAcwBbACQAaQBkAF0AIAA9ACAAQAB7ACAAcgBhAHcAPQAkAHIAYQB3ADsAIABjAHUAcgA9ACQAYwB1AHIAIAB9AAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIwAgAFAAbwB3AGUAcgAtAE8AbgAgAEgAbwB1AHIAcwAgAEkARAA9ADkACgAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAGEAdAB0AHIAcwAuAEMAbwBuAHQAYQBpAG4AcwBLAGUAeQAoADkAKQApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAaAAgAD0AIAAkAGEAdAB0AHIAcwBbADkAXQAuAHIAYQB3ADsAIAAkAGQAYQB5AHMAIAA9ACAAWwBNAGEAdABoAF0AOgA6AEYAbABvAG8AcgAoACQAaAAvADIANAApAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABwAG8AdwBlAHIATwBuAEgAbwB1AHIAcwAgAD0AIAAiACQAaAAgAGcAaQBvACAAKAB+ACQAZABhAHkAcwAgAG4AZwBhAHkAKQAiAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIwAgAEgAZQBhAGwAdABoADoAIABJAEQAIAAyADMAMQAgACgAUwBTAEQAIABMAGkAZgBlACAATABlAGYAdAApACwAIAAxADcANwAgACgAVwBlAGEAcgAgAEwAZQB2AGUAbABpAG4AZwAgAEMAbwB1AG4AdAApACwAIAAyADAAMgAsACAAMQA2ADkACgAgACAAIAAgACAAIAAgACAAJABoAGkAZAAgAD0AIABAACgAMgAzADEALAAxADcANwAsADIAMAAyACwAMQA2ADkAKQAgAHwAIABXAGgAZQByAGUALQBPAGIAagBlAGMAdAAgAHsAIAAkAGEAdAB0AHIAcwAuAEMAbwBuAHQAYQBpAG4AcwBLAGUAeQAoACQAXwApACAAfQAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBGAGkAcgBzAHQAIAAxAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABoAGkAZAApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAdgAgAD0AIAAkAGEAdAB0AHIAcwBbACQAaABpAGQAXQAuAGMAdQByAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABoAGUAYQBsAHQAaABTAHQAcgAgACAAIAA9ACAAIgAkAHYAJQAiAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABoAGUAYQBsAHQAaABDAG8AbABvAHIAIAA9ACAAaQBmACAAKAAkAHYAIAAtAGcAdAAgADcAMAApACAAewAgACcARwByAGUAZQBuACcAIAB9ACAAZQBsAHMAZQBpAGYAIAAoACQAdgAgAC0AZwB0ACAANAAwACkAIAB7ACAAJwBZAGUAbABsAG8AdwAnACAAfQAgAGUAbABzAGUAIAB7ACAAJwBSAGUAZAAnACAAfQAKACAAIAAgACAAIAAgACAAIAB9ACAAZQBsAHMAZQBpAGYAIAAoACQAYQB0AHQAcgBzAC4AQwBvAG4AdABhAGkAbgBzAEsAZQB5ACgANQApACAALQBvAHIAIAAkAGEAdAB0AHIAcwAuAEMAbwBuAHQAYQBpAG4AcwBLAGUAeQAoADEAOQA3ACkAIAAtAG8AcgAgACQAYQB0AHQAcgBzAC4AQwBvAG4AdABhAGkAbgBzAEsAZQB5ACgAMQA5ADgAKQApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYgBhAGQAIAA9ACAAMAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAYgBpAGQAIABpAG4AIABAACgANQAsADEAOQA3ACwAMQA5ADgAKQApACAAewAgAGkAZgAgACgAJABhAHQAdAByAHMALgBDAG8AbgB0AGEAaQBuAHMASwBlAHkAKAAkAGIAaQBkACkAKQAgAHsAIAAkAGIAYQBkACAAKwA9ACAAJABhAHQAdAByAHMAWwAkAGIAaQBkAF0ALgByAGEAdwAgAH0AIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABoAGUAYQBsAHQAaABTAHQAcgAgAD0AIABpAGYAIAAoACQAYgBhAGQAIAAtAGUAcQAgADAAKQAgAHsAIAAnADEAMAAwACUAIAAoAEsAaABvAG4AZwAgAGMAbwAgAGIAYQBkACAAcwBlAGMAdABvAHIAKQAnACAAfQAgAGUAbABzAGUAIAB7ACAAIgBDAGEAbgBoACAAYgBhAG8AIQAgACQAYgBhAGQAIABzAGUAYwB0AG8AcgAgAGwAbwBpACIAIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABoAGUAYQBsAHQAaABDAG8AbABvAHIAIAA9ACAAaQBmACAAKAAkAGIAYQBkACAALQBlAHEAIAAwACkAIAB7ACAAJwBHAHIAZQBlAG4AJwAgAH0AIABlAGwAcwBlACAAewAgACcAUgBlAGQAJwAgAH0ACgAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAfQAKAAoAIAAgACAAIAAjACAAJQAgAHMAdQAgAGQAdQBuAGcACgAgACAAIAAgACQAdQBzAGUAZABTAHQAcgAgAD0AIAAnAE4ALwBBACcAOwAgACQAdQBzAGUAZABDAG8AbABvAHIAIAA9ACAAJwBEAGEAcgBrAEcAcgBhAHkAJwAKACAAIAAgACAAaQBmACAAKAAkAHMAaQB6AGUAVABvAHQAYQBsACAALQBnAHQAIAAwACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACQAdQBwAGMAdAAgACAAIAAgAD0AIABbAE0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAKAAkAHMAaQB6AGUAVABvAHQAYQBsAC0AJABmAHIAZQBlAFQAbwB0AGEAbAApAC8AJABzAGkAegBlAFQAbwB0AGEAbAAqADEAMAAwACwAMQApAAoAIAAgACAAIAAgACAAIAAgACQAZgByAGUAZQBHAEIAIAAgAD0AIABbAE0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJABmAHIAZQBlAFQAbwB0AGEAbAAvADEARwBCACwAMQApAAoAIAAgACAAIAAgACAAIAAgACQAdQBzAGUAZABHAEIAIAAgAD0AIABbAE0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAKAAkAHMAaQB6AGUAVABvAHQAYQBsAC0AJABmAHIAZQBlAFQAbwB0AGEAbAApAC8AMQBHAEIALAAxACkACgAgACAAIAAgACAAIAAgACAAJAB1AHMAZQBkAEMAbwBsAG8AcgAgAD0AIABpAGYAIAAoACQAdQBwAGMAdAAgAC0AbAB0ACAANwAwACkAIAB7ACcARwByAGUAZQBuACcAfQAgAGUAbABzAGUAaQBmACAAKAAkAHUAcABjAHQAIAAtAGwAdAAgADkAMAApACAAewAnAFkAZQBsAGwAbwB3ACcAfQAgAGUAbABzAGUAIAB7ACcAUgBlAGQAJwB9AAoAIAAgACAAIAAgACAAIAAgACQAdQBzAGUAZABTAHQAcgAgAD0AIAAiACQAewB1AHAAYwB0AH0AJQAgACAAKABEAGEAIABkAHUAbgBnADoAIAAkAHsAdQBzAGUAZABHAEIAfQAgAEcAQgAgACAALwAgACAAQwBvAG4AIABsAGEAaQA6ACAAJAB7AGYAcgBlAGUARwBCAH0AIABHAEIAKQAiAAoAIAAgACAAIAB9AAoACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgAgACAAIAAgAFIAbwB3ACAAJwBNAG8AZABlAGwAJwAgACAAIAAgACAAIAAgACAAIAAgACAAJABtAG8AZABlAGwAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAFcAaABpAHQAZQAnAAoAIAAgACAAIABSAG8AdwAgACcATABvAGEAaQAnACAAIAAgACAAIAAgACAAIAAgACAAIAAgACIAJABkAHIAaQB2AGUAVAB5AHAAZQAgACAAWwAkAG0AZQBkAGkAYQBMAGEAYgBlAGwAXQAiACAAIAAgACAAJwBDAHkAYQBuACcACgAgACAAIAAgAFIAbwB3ACAAJwBEAHUAbgBnACAAbAB1AG8AbgBnACAAZwBvAGMAJwAgACAAIgAkAHIAYQB3AEcAQgAgAEcAQgAgACAAKABXAGkAbgBkAG8AdwBzADoAIAAkAHIAZQBhAGwARwBCACAARwBCACkAIgAgACcARwByAGUAZQBuACcACgAgACAAIAAgAFIAbwB3ACAAJwBTAHUAIABkAHUAbgBnACcAIAAgACAAIAAgACAAIAAgACAAJAB1AHMAZQBkAFMAdAByACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHUAcwBlAGQAQwBvAGwAbwByAAoAIAAgACAAIABSAG8AdwAgACcAUwB1AGMAIABrAGgAbwBlACcAIAAgACAAIAAgACAAIAAgACQAaABlAGEAbAB0AGgAUwB0AHIAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABoAGUAYQBsAHQAaABDAG8AbABvAHIACgAgACAAIAAgAFIAbwB3ACAAJwBUAGgAbwBpACAAZwBpAGEAbgAgAGMAaABhAHkAJwAgACAAJABwAG8AdwBlAHIATwBuAEgAbwB1AHIAcwAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAEQAYQByAGsARwByAGEAeQAnAAoAIAAgACAAIABSAG8AdwAgACcAUwBlAHIAaQBhAGwAIABOAHUAbQBiAGUAcgAnACAAIAAgACQAZABpAHMAawAuAFMAZQByAGkAYQBsAE4AdQBtAGIAZQByACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJwBEAGEAcgBrAEcAcgBhAHkAJwAKAH0ACgAKACMAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUgAFAASQBOACAAACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQoAUwBlAGMAIAAnAFAASQBOACAAKABCAEEAVABUAEUAUgBZACkAJwAKACQAYgBhAHQAVwBpAG4AIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBCAGEAdAB0AGUAcgB5ACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADEACgBpAGYAIAAoACQAYgBhAHQAVwBpAG4AKQAgAHsACgAgACAAIAAgACMAIABEAG8AYwAgAFcATQBJACAAYgBhAHQAdABlAHIAeQAgAG4AYQBtAGUAcwBwAGEAYwBlAAoAIAAgACAAIAAkAGIAYQB0AFMAdABhAHQAaQBjACAAIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIAAtAE4AYQBtAGUAcwBwAGEAYwBlACAAcgBvAG8AdABcAHcAbQBpACAALQBDAGwAYQBzAHMATgBhAG0AZQAgAEIAYQB0AHQAZQByAHkAUwB0AGEAdABpAGMARABhAHQAYQAgACAAIAAgACAAIAAgACAAIAAgADIAPgAkAG4AdQBsAGwAIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQAKACAAIAAgACAAJABiAGEAdABGAHUAbABsACAAIAAgACAAPQAgAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAALQBOAGEAbQBlAHMAcABhAGMAZQAgAHIAbwBvAHQAXAB3AG0AaQAgAC0AQwBsAGEAcwBzAE4AYQBtAGUAIABCAGEAdAB0AGUAcgB5AEYAdQBsAGwAQwBoAGEAcgBnAGUAZABDAGEAcABhAGMAaQB0AHkAIAAyAD4AJABuAHUAbABsACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADEACgAgACAAIAAgACQAYgBhAHQARAB5AG4AIAAgACAAIAAgAD0AIABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAC0ATgBhAG0AZQBzAHAAYQBjAGUAIAByAG8AbwB0AFwAdwBtAGkAIAAtAEMAbABhAHMAcwBOAGEAbQBlACAAQgBhAHQAdABlAHIAeQBTAHQAYQB0AHUAcwAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAMgA+ACQAbgB1AGwAbAAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBGAGkAcgBzAHQAIAAxAAoACgAgACAAIAAgACQAZABlAHMAaQBnAG4AQwBBAFAAIAA9ACAAaQBmACAAKAAkAGIAYQB0AFMAdABhAHQAaQBjACAALQBhAG4AZAAgACQAYgBhAHQAUwB0AGEAdABpAGMALgBEAGUAcwBpAGcAbgBlAGQAQwBhAHAAYQBjAGkAdAB5ACAALQBnAHQAIAAwACkAIAB7ACAAWwBpAG4AdABdACQAYgBhAHQAUwB0AGEAdABpAGMALgBEAGUAcwBpAGcAbgBlAGQAQwBhAHAAYQBjAGkAdAB5ACAAfQAgAGUAbABzAGUAIAB7ACAAMAAgAH0ACgAgACAAIAAgACQAZgB1AGwAbABDAEEAUAAgACAAIAA9ACAAaQBmACAAKAAkAGIAYQB0AEYAdQBsAGwAIAAgACAALQBhAG4AZAAgACQAYgBhAHQARgB1AGwAbAAuAEYAdQBsAGwAQwBoAGEAcgBnAGUAZABDAGEAcABhAGMAaQB0AHkAIAAtAGcAdAAgADAAKQAgAHsAIABbAGkAbgB0AF0AJABiAGEAdABGAHUAbABsAC4ARgB1AGwAbABDAGgAYQByAGcAZQBkAEMAYQBwAGEAYwBpAHQAeQAgAH0AIABlAGwAcwBlACAAewAgADAAIAB9AAoACgAgACAAIAAgACMAIABGAGEAbABsAGIAYQBjAGsAOgAgAGQAbwBjACAAdAB1ACAAcABvAHcAZQByAGMAZgBnACAALwBiAGEAdAB0AGUAcgB5AHIAZQBwAG8AcgB0ACAAbgBlAHUAIABXAE0ASQAgAGsAaABvAG4AZwAgAGMAbwAKACAAIAAgACAAaQBmACAAKAAkAGQAZQBzAGkAZwBuAEMAQQBQACAALQBlAHEAIAAwACAALQBvAHIAIAAkAGYAdQBsAGwAQwBBAFAAIAAtAGUAcQAgADAAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJAByAHAAdAAgAD0AIAAiACQAZQBuAHYAOgBUAEUATQBQAFwAYgBhAHQAcgBlAHAAbwByAHQALgB4AG0AbAAiAAoAIAAgACAAIAAgACAAIAAgAHAAbwB3AGUAcgBjAGYAZwAgAC8AYgBhAHQAdABlAHIAeQByAGUAcABvAHIAdAAgAC8AbwB1AHQAcAB1AHQAIAAkAHIAcAB0ACAALwB4AG0AbAAgADIAPgAkAG4AdQBsAGwAIAB8ACAATwB1AHQALQBOAHUAbABsAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAkAHIAcAB0ACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwB4AG0AbABdACQAeABtAGwAIAA9ACAARwBlAHQALQBDAG8AbgB0AGUAbgB0ACAAJAByAHAAdAAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbgBzACAAPQAgACQAeABtAGwALgBCAGEAdAB0AGUAcgB5AFIAZQBwAG8AcgB0AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAG4AcwApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiADAAIAA9ACAAJABuAHMALgBCAGEAdAB0AGUAcgBpAGUAcwAuAEIAYQB0AHQAZQByAHkAIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAGIAMAApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAZABlAHMAaQBnAG4AQwBBAFAAIAAtAGUAcQAgADAAIAAtAGEAbgBkACAAJABiADAALgBEAGUAcwBpAGcAbgBDAGEAcABhAGMAaQB0AHkAKQAgACAAIAAgACAAewAgACQAZABlAHMAaQBnAG4AQwBBAFAAIAA9ACAAWwBpAG4AdABdACQAYgAwAC4ARABlAHMAaQBnAG4AQwBhAHAAYQBjAGkAdAB5ACAAfQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAZgB1AGwAbABDAEEAUAAgACAAIAAtAGUAcQAgADAAIAAtAGEAbgBkACAAJABiADAALgBGAHUAbABsAEMAaABhAHIAZwBlAEMAYQBwAGEAYwBpAHQAeQApACAAewAgACQAZgB1AGwAbABDAEEAUAAgACAAIAA9ACAAWwBpAG4AdABdACQAYgAwAC4ARgB1AGwAbABDAGgAYQByAGcAZQBDAGEAcABhAGMAaQB0AHkAIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACQAcgBwAHQAIAAtAEYAbwByAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9AAoACgAgACAAIAAgAGkAZgAgACgAJABkAGUAcwBpAGcAbgBDAEEAUAAgAC0AZwB0ACAAMAAgAC0AYQBuAGQAIAAkAGYAdQBsAGwAQwBBAFAAIAAtAGcAdAAgADAAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJABoAGUAYQBsAHQAaABQAGMAdAAgAD0AIABbAE0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJABmAHUAbABsAEMAQQBQACAALwAgACQAZABlAHMAaQBnAG4AQwBBAFAAIAAqACAAMQAwADAALAAgADEAKQAKACAAIAAgACAAIAAgACAAIAAkAHcAZQBhAHIAUABjAHQAIAAgACAAPQAgAFsATQBhAHQAaABdADoAOgBSAG8AdQBuAGQAKAAxADAAMAAgAC0AIAAkAGgAZQBhAGwAdABoAFAAYwB0ACwAIAAxACkACgAgACAAIAAgACAAIAAgACAAJABoAEMAbwBsAG8AcgAgACAAIAAgAD0AIABpAGYAIAAoACQAaABlAGEAbAB0AGgAUABjAHQAIAAtAGcAZQAgADgAMAApACAAewAnAEcAcgBlAGUAbgAnAH0AIABlAGwAcwBlAGkAZgAgACgAJABoAGUAYQBsAHQAaABQAGMAdAAgAC0AZwBlACAANgAwACkAIAB7ACcAWQBlAGwAbABvAHcAJwB9ACAAZQBsAHMAZQAgAHsAJwBSAGUAZAAnAH0ACgAgACAAIAAgACAAIAAgACAAUgBvAHcAIAAnAEQAdQBuAGcAIABsAHUAbwBuAGcAIAB0AGgAaQBlAHQAIABrAGUAJwAgACAAIAAiACQAZABlAHMAaQBnAG4AQwBBAFAAIABtAFcAaAAiACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAEQAYQByAGsARwByAGEAeQAnAAoAIAAgACAAIAAgACAAIAAgAFIAbwB3ACAAJwBEAHUAbgBnACAAbAB1AG8AbgBnACAAaABpAGUAbgAgAHQAYQBpACcAIAAgACAAIgAkAGYAdQBsAGwAQwBBAFAAIABtAFcAaAAiACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJwBDAHkAYQBuACcACgAgACAAIAAgACAAIAAgACAAUgBvAHcAIAAnAFMAdQBjACAAawBoAG8AZQAgAHAAaQBuACcAIAAgACAAIAAgACAAIAAgACAAIAAiACQAaABlAGEAbAB0AGgAUABjAHQAJQAgACAAKABEAGEAIABjAGgAYQBpADoAIAAkAHcAZQBhAHIAUABjAHQAJQApACIAIAAkAGgAQwBvAGwAbwByAAoAIAAgACAAIAB9ACAAZQBsAHMAZQAgAHsACgAgACAAIAAgACAAIAAgACAAUgBvAHcAIAAnAEQAdQBuAGcAIABsAHUAbwBuAGcAJwAgACAAJwBLAGgAbwBuAGcAIABkAG8AYwAgAGQAdQBvAGMAIAAoAGMAYQBuACAAYwBoAGEAeQAgAEEAZABtAGkAbgApACcAIAAgACcARABhAHIAawBHAHIAYQB5ACcACgAgACAAIAAgAH0ACgAKACAAIAAgACAAJABjAHUAcgBQAGMAdAAgACAAPQAgACQAYgBhAHQAVwBpAG4ALgBFAHMAdABpAG0AYQB0AGUAZABDAGgAYQByAGcAZQBSAGUAbQBhAGkAbgBpAG4AZwAKACAAIAAgACAAJABzAHQAYQB0AHUAcwAgACAAPQAgAGkAZgAgACgAJABiAGEAdABEAHkAbgAgAC0AYQBuAGQAIAAkAGIAYQB0AEQAeQBuAC4AQwBoAGEAcgBnAGkAbgBnACkAIAB7ACcAIABbAEQAYQBuAGcAIABzAGEAYwBdACcAfQAgAGUAbABzAGUAaQBmACAAKAAkAGIAYQB0AEQAeQBuACAALQBhAG4AZAAgACQAYgBhAHQARAB5AG4ALgBEAGkAcwBjAGgAYQByAGcAaQBuAGcAKQAgAHsAJwAgAFsARABhAG4AZwAgAHgAYQBdACcAfQAgAGUAbABzAGUAIAB7ACcAJwB9AAoAIAAgACAAIAAkAGIAQwBvAGwAbwByACAAIAA9ACAAaQBmACAAKAAkAGMAdQByAFAAYwB0ACAALQBnAGUAIAA1ADAAKQAgAHsAJwBHAHIAZQBlAG4AJwB9ACAAZQBsAHMAZQBpAGYAIAAoACQAYwB1AHIAUABjAHQAIAAtAGcAZQAgADIAMAApACAAewAnAFkAZQBsAGwAbwB3ACcAfQAgAGUAbABzAGUAIAB7ACcAUgBlAGQAJwB9AAoAIAAgACAAIABSAG8AdwAgACcAUABpAG4AIABoAGkAZQBuACAAdABhAGkAJwAgACAAIgAkAGMAdQByAFAAYwB0ACUAJABzAHQAYQB0AHUAcwAiACAAIAAkAGIAQwBvAGwAbwByAAoACgAgACAAIAAgACQAYwB5AGMAbABlACAAPQAgAGkAZgAgACgAJABiAGEAdABTAHQAYQB0AGkAYwAgAC0AYQBuAGQAIAAkAGIAYQB0AFMAdABhAHQAaQBjAC4AQwB5AGMAbABlAEMAbwB1AG4AdAAgAC0AZwB0ACAAMAApACAAewAgACIAJAAoACQAYgBhAHQAUwB0AGEAdABpAGMALgBDAHkAYwBsAGUAQwBvAHUAbgB0ACkAIABsAGEAbgAiACAAfQAgAGUAbABzAGUAIAB7ACAAJwBOAC8AQQAnACAAfQAKACAAIAAgACAAUgBvAHcAIAAnAFMAbwAgAGwAYQBuACAAcwBhAGMAJwAgACAAJABjAHkAYwBsAGUAIAAgACcARABhAHIAawBHAHIAYQB5ACcACgB9ACAAZQBsAHMAZQAgAHsACgAgACAAIAAgAFIAbwB3ACAAJwBUAHIAYQBuAGcAIAB0AGgAYQBpACcAIAAgACcASwBoAG8AbgBnACAAYwBvACAAcABpAG4AIAAoAG0AYQB5ACAAYgBhAG4AIAAvACAAUABDACkAJwAgACAAJwBEAGEAcgBrAEcAcgBhAHkAJwAKAH0ACgAKACMAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUgAE0AQQBJAE4AQgBPAEEAUgBEACAALwAgAEIASQBPAFMAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUKAFMAZQBjACAAJwBNAEEASQBOAEIATwBBAFIARAAgAC8AIABCAEkATwBTACcACgAkAG0AYgAgAD0AIABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAFcAaQBuADMAMgBfAEIAYQBzAGUAQgBvAGEAcgBkAAoAUgBvAHcAIAAnAE0AYQBpAG4AYgBvAGEAcgBkACcAIAAgACAAIAAiACQAKAAkAG0AYgAuAE0AYQBuAHUAZgBhAGMAdAB1AHIAZQByACkAIAAkACgAJABtAGIALgBQAHIAbwBkAHUAYwB0ACkAIgAgACAAJwBXAGgAaQB0AGUAJwAKACQAYgAgACAAPQAgAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8AQgBJAE8AUwAKAFIAbwB3ACAAJwBCAEkATwBTACAAVgBlAHIAcwBpAG8AbgAnACAAJABiAC4AUwBNAEIASQBPAFMAQgBJAE8AUwBWAGUAcgBzAGkAbwBuACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACcARABhAHIAawBHAHIAYQB5ACcACgBSAG8AdwAgACcAUwBlAHIAaQBhAGwAIABNAGEAeQAnACAAIAAgACQAYgAuAFMAZQByAGkAYQBsAE4AdQBtAGIAZQByACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAnAEQAYQByAGsARwByAGEAeQAnAAoACgAjACAAACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUgAFcASQBGAEkAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlCgBTAGUAYwAgACcAVwBJAEYASQAgAEQAQQAgAEwAVQBVACAAKAAqACkAJwAKACQAdwBmACAAPQAgAG4AZQB0AHMAaAAgAHcAbABhAG4AIABzAGgAbwB3ACAAcAByAG8AZgBpAGwAZQBzACAAfAAgAFMAZQBsAGUAYwB0AC0AUwB0AHIAaQBuAGcAIAAnAEEAbABsACAAVQBzAGUAcgAgAFAAcgBvAGYAaQBsAGUAJwAgAHwAIABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7ACAAKAAkAF8AIAAtAHMAcABsAGkAdAAgACcAOgAnACkAWwAxAF0ALgBUAHIAaQBtACgAKQAgAH0ACgBpAGYAIAAoACQAdwBmACkAIAB7AAoAIAAgACAAIAAkAGkAIAA9ACAAMQAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABwACAAaQBuACAAJAB3AGYAKQAgAHsACgAgACAAIAAgACAAIAAgACAAUgBvAHcAIAAiACAAIABbACQAaQBdACIAIAAgACQAcAAgACAAJwBHAHIAZQBlAG4AJwAKACAAIAAgACAAIAAgACAAIAAkAGkAKwArAAoAIAAgACAAIAB9AAoAfQAgAGUAbABzAGUAIAB7AAoAIAAgACAAIABSAG8AdwAgACcAVAByAGEAbgBnACAAdABoAGEAaQAnACAAIAAnAEsAaABvAG4AZwAgAGMAbwAgAG0AYQBuAGcAIABuAGEAbwAgAGQAYQAgAGIAaQBlAHQAIAAvACAASwBoAG8AbgBnACAAYwBvACAAVwBpAEYAaQAnACAAIAAnAEQAYQByAGsARwByAGEAeQAnAAoAfQAKAAoAIwAgAAAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJSAARgBPAE8AVABFAFIAIAAAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQAlACUAJQoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAEwAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAgACAAIAAgAE4AaABhAG4AIABFAG4AdABlAHIAIABkAGUAIABxAHUAYQB5ACAAbABhAGkAIABtAGUAbgB1AC4ALgAuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARABhAHIAawBHAHIAYQB5AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAFIAZQBhAGQALQBIAG8AcwB0ACAAfAAgAE8AdQB0AC0ATgB1AGwAbAAKAA==
mode con: cols=92 lines=45
goto MENU

:: ============================================================
:BACKUP_DRIVER
cls
echo.
echo  ============================================================
echo                   QUAN LY DRIVER
echo  ============================================================
echo.
set "backupPath=%USERPROFILE%\Desktop\Driver_Backup"
echo   Thu muc backup: %backupPath%
echo.
echo   [1] Backup tat ca driver hien tai
echo   [2] Restore (cai lai) driver tu ban backup
echo   [0] Quay lai
echo.
set "dchoice="
set /p dchoice="  Chon (0-2): "
if "%dchoice%"=="0" goto MENU
if "%dchoice%"=="1" goto DO_BACKUP
if "%dchoice%"=="2" goto DO_RESTORE
goto BACKUP_DRIVER

:DO_BACKUP
cls
echo.
echo  ============================================================
echo                    BACKUP DRIVER
echo  ============================================================
echo.
echo  Thu muc luu: %backupPath%
echo.
if not exist "%backupPath%" (
    echo  [*] Tao thu muc dich...
    mkdir "%backupPath%"
)
echo  [*] Dang backup tat ca driver, vui long cho...
echo.
dism /online /export-driver /destination:"%backupPath%"
echo.
if %errorlevel%==0 (
    echo  [OK] Backup driver thanh cong!
    echo       Luu tai: %backupPath%
) else (
    echo  [LOI] Backup that bai!
    echo        - Hay chay file nay voi quyen Administrator
    echo        - Click phai vao file .cmd ^> Run as administrator
)
echo.
pause
goto MENU

:DO_RESTORE
cls
echo.
echo  ============================================================
echo                   RESTORE DRIVER
echo  ============================================================
echo.
if not exist "%backupPath%" (
    echo  [!] Khong tim thay thu muc backup tai:
    echo      %backupPath%
    echo.
    echo      Hay chay Backup Driver truoc!
    echo.
    pause
    goto MENU
)
echo  Thu muc backup: %backupPath%
echo.
set "confirm="
set /p confirm="  Xac nhan cai lai TAT CA driver trong thu muc? (Y/N): "
if /i not "%confirm%"=="Y" (
    echo  [*] Huy bo.
    timeout /t 2 >nul
    goto MENU
)
echo.
echo  [*] Dang cai lai driver... (co the mat vai phut)
echo.
pnputil /add-driver "%backupPath%\*.inf" /subdirs /install
echo.
if %errorlevel%==0 (
    echo  [OK] Restore driver thanh cong!
) else (
    echo  [!] Mot so driver co the da ton tai - day la binh thuong.
)
echo.
set "reboot="
set /p reboot="  Khoi dong lai may ngay bay gio? (Y/N): "
if /i "%reboot%"=="Y" (
    shutdown /r /t 10 /c "Khoi dong lai de ap dung driver"
    echo  [i] May se khoi dong lai sau 10 giay. Nhan Ctrl+C de huy.
    pause
)
goto MENU

:: ============================================================
:SAVE_KEY
cls
echo.
echo  ============================================================
echo        SAO LUU BAN QUYEN KEY WINDOWS / OFFICE
echo  ============================================================
echo.
set "keyFile=%USERPROFILE%\Desktop\ProductKey_Backup.txt"
echo ============================================ > "%keyFile%"
echo       PRODUCT KEY BACKUP >> "%keyFile%"
echo       %date% %time% >> "%keyFile%"
echo ============================================ >> "%keyFile%"
echo. >> "%keyFile%"
echo  [*] Dang lay Windows Key...
echo === WINDOWS OEM KEY === >> "%keyFile%"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$k=(Get-CimInstance -Query 'SELECT OA3xOriginalProductKey FROM SoftwareLicensingService').OA3xOriginalProductKey; if($k){$k}else{'Khong tim thay OEM key'}" >> "%keyFile%"
echo. >> "%keyFile%"
echo === WINDOWS PRODUCT ID === >> "%keyFile%"
powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-CimInstance Win32_OperatingSystem).SerialNumber" >> "%keyFile%"
echo. >> "%keyFile%"
echo === OFFICE KEY (neu co) === >> "%keyFile%"
reg query "HKLM\SOFTWARE\Microsoft\Office" /s /v ProductKey 2>nul >> "%keyFile%"
reg query "HKLM\SOFTWARE\WOW6432Node\Microsoft\Office" /s /v ProductKey 2>nul >> "%keyFile%"
echo.
echo  [OK] Da luu key tai: %keyFile%
echo.
echo  [*] Windows Key hien tai:
powershell -NoProfile -ExecutionPolicy Bypass -Command "$k=(Get-CimInstance -Query 'SELECT OA3xOriginalProductKey FROM SoftwareLicensingService').OA3xOriginalProductKey; if($k){$k}else{'Khong tim thay OEM key'}"
echo.
pause
goto MENU

:: ============================================================
:ACTIVATE
cls
echo.
echo  ============================================================
echo        KICH HOAT WINDOWS / OFFICE  (MAS Tool)
echo  ============================================================
echo.
echo  Cong cu: Microsoft Activation Scripts (massgrave.dev)
echo.
set "confirm="
set /p confirm="  Nhap Y de chay, N de quay lai: "
if /i "%confirm%"=="Y" (
    echo.
    echo  [*] Dang khoi chay cong cu kich hoat...
    powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://get.activated.win | iex"
) else (
    echo  [*] Huy bo.
    timeout /t 2 >nul
)
goto MENU

:: ============================================================
:ZALO
cls
echo.
echo  ============================================================
echo                 SAO LUU DU LIEU ZALO
echo  ============================================================
echo.
set "zaloSrc=%APPDATA%\Zalo"
set "zaloBackup=%USERPROFILE%\Desktop\Zalo_Backup"
if exist "%zaloSrc%" (
    echo  [*] Nguon : %zaloSrc%
    echo  [*] Dich  : %zaloBackup%
    echo.
    echo  [*] Dang sao luu... co the mat vai phut.
    xcopy "%zaloSrc%" "%zaloBackup%" /E /I /H /Y /Q
    if %errorlevel%==0 (
        echo.
        echo  [OK] Sao luu Zalo thanh cong!
        echo       Luu tai: %zaloBackup%
    ) else (
        echo  [LOI] Sao luu that bai!
    )
) else (
    echo  [!] Khong tim thay thu muc Zalo tai: %zaloSrc%
)
echo.
pause
goto MENU

:: ============================================================
:BITLOCKER
cls
echo.
echo  ============================================================
echo                    TAT BITLOCKER
echo  ============================================================
echo.
echo  [*] Trang thai BitLocker hien tai:
echo.
manage-bde -status 2>nul
if %errorlevel% neq 0 (
    echo  [!] Khong the kiem tra. May co the khong co BitLocker.
    echo.
    pause
    goto MENU
)
echo.
set "driveLetter="
set /p driveLetter="  Nhap ten o dia can tat (vd: C, D): "
if "%driveLetter%"=="" goto MENU
echo.
set "confirm="
set /p confirm="  Xac nhan tat BitLocker tren o %driveLetter%: ? (Y/N): "
if /i "%confirm%"=="Y" (
    manage-bde -off %driveLetter%:
    echo.
    manage-bde -status %driveLetter%:
) else (
    echo  [*] Huy bo.
)
echo.
pause
goto MENU

:: ============================================================
:CLEANUP
cls
echo.
echo  ============================================================
echo                 DON DEP TEP TIN RAC
echo  ============================================================
echo.
echo  [1/5] Xoa Temp he thong...
del /f /s /q "%SystemRoot%\Temp\*" >nul 2>&1
echo  [2/5] Xoa Temp nguoi dung...
del /f /s /q "%TEMP%\*" >nul 2>&1
echo  [3/5] Xoa Prefetch...
del /f /s /q "%SystemRoot%\Prefetch\*" >nul 2>&1
echo  [4/5] Xoa Windows Update cache...
net stop wuauserv >nul 2>&1
del /f /s /q "%SystemRoot%\SoftwareDistribution\Download\*" >nul 2>&1
net start wuauserv >nul 2>&1
echo  [5/5] Xoa Recent files...
del /f /s /q "%APPDATA%\Microsoft\Windows\Recent\*" >nul 2>&1
echo.
echo  [OK] Don dep hoan tat!
echo.
pause
goto MENU

:: ============================================================
:DISABLE_UPDATE
cls
echo.
echo  ============================================================
echo                 TAT WINDOWS UPDATE
echo  ============================================================
echo.
echo   [1] Tam dung update 35 ngay
echo   [2] Tat hoan toan (vo hieu dich vu)
echo   [3] Bat lai Windows Update
echo   [0] Quay lai
echo.
set "uchoice="
set /p uchoice="  Chon (0-3): "
if "%uchoice%"=="0" goto MENU
if "%uchoice%"=="1" (
    echo  [*] Dang tam dung Windows Update...
    sc stop wuauserv >nul 2>&1
    reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v NoAutoUpdate /t REG_DWORD /d 1 /f >nul 2>&1
    reg add "HKLM\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v FlightSettingsMaxPauseDays /t REG_DWORD /d 35 /f >nul 2>&1
    echo  [OK] Da tam dung update 35 ngay!
)
if "%uchoice%"=="2" (
    echo  [*] Dang tat hoan toan Windows Update...
    sc stop wuauserv >nul 2>&1
    sc config wuauserv start= disabled >nul 2>&1
    sc stop UsoSvc >nul 2>&1
    sc config UsoSvc start= disabled >nul 2>&1
    reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v NoAutoUpdate /t REG_DWORD /d 1 /f >nul 2>&1
    echo  [OK] Da tat hoan toan Windows Update!
)
if "%uchoice%"=="3" (
    echo  [*] Dang bat lai Windows Update...
    sc config wuauserv start= auto >nul 2>&1
    sc start wuauserv >nul 2>&1
    sc config UsoSvc start= auto >nul 2>&1
    sc start UsoSvc >nul 2>&1
    reg delete "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v NoAutoUpdate /f >nul 2>&1
    echo  [OK] Da bat lai Windows Update!
)
echo.
pause
goto MENU

:: ============================================================
:DISABLE_DEFENDER
cls
echo.
echo  ============================================================
echo               TAT WINDOWS DEFENDER
echo  ============================================================
echo.
echo   [1] Tat Real-time Protection (tam thoi)
echo   [2] Tat hoan toan qua Registry
echo   [3] Bat lai Windows Defender
echo   [0] Quay lai
echo.
set "dchoice="
set /p dchoice="  Chon (0-3): "
if "%dchoice%"=="0" goto MENU
if "%dchoice%"=="1" (
    echo  [*] Dang tat Real-time Protection...
    powershell -ExecutionPolicy Bypass -Command "Set-MpPreference -DisableRealtimeMonitoring $true" 2>nul
    echo  [OK] Da tat Real-time Protection!
)
if "%dchoice%"=="2" (
    echo  [*] Dang tat Windows Defender...
    reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /t REG_DWORD /d 1 /f >nul 2>&1
    reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableRealtimeMonitoring /t REG_DWORD /d 1 /f >nul 2>&1
    powershell -ExecutionPolicy Bypass -Command "Set-MpPreference -DisableRealtimeMonitoring $true" 2>nul
    echo  [OK] Da tat Windows Defender!
    echo  [i] Win 11: Can tat Tamper Protection trong Windows Security truoc.
)
if "%dchoice%"=="3" (
    echo  [*] Dang bat lai Windows Defender...
    reg delete "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /f >nul 2>&1
    reg delete "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableRealtimeMonitoring /f >nul 2>&1
    powershell -ExecutionPolicy Bypass -Command "Set-MpPreference -DisableRealtimeMonitoring $false" 2>nul
    sc start WinDefend >nul 2>&1
    echo  [OK] Da bat lai Windows Defender!
)
echo.
pause
goto MENU

:: ============================================================
:EXIT
cls
echo.
echo  Cam on ban da su dung! Tam biet!
echo.
timeout /t 2 >nul
exit /b
